"""Enumeration of the environments variables names."""
from enum import Enum


class EnvironmentVars(Enum):
    """Environment variables names."""
    # Jobs
    JOB_UUID = "JOB_UUID"
    TYPE_BACKUP = "TYPE_BACKUP"
    PATH_WORK_DIR = "PATH_WORK_DIR"
    PATH_LOG_FILE = "PATH_LOG_FILE"

    # Job Restoration
    RESTORE_ARCHIVE_NAME = "RESTORE_ARCHIVE_NAME"
    RESTORE_OVERWRITE = "RESTORE_OVERWRITE"

    # Job Backup
    # Maintenance mode
    MAINTENANCE_NAMESPACE = "MAINTENANCE_NAMESPACE"
    MAINTENANCE_INGRESS_NAME = "MAINTENANCE_INGRESS_NAME"
    MAINTENANCE_INGRESS_CLASS_NAME = "MAINTENANCE_INGRESS_CLASS_NAME"
    MAINTENANCE_CONFIG_MAP_NAME = "MAINTENANCE_CONFIG_MAP_NAME"
    MAINTENANCE_CONFIG_MAP_KEY = "MAINTENANCE_CONFIG_MAP_KEY"
    MAINTENANCE_CONFIG_MAP_VALUE = "MAINTENANCE_CONFIG_MAP_VALUE"

    # Service CQL
    CQLSH_COMMAND = "CQLSH_COMMAND"
    CQL_HOST = "CQL_HOST"
    CQL_KEYSPACES = "CQL_KEYSPACES"
    CQL_TABLES = "CQL_TABLES"

    # Service Minio
    PATH_MC = "PATH_MINIO_CLIENT"
    PATH_MC_CONFIG = "PATH_MINIO_CLIENT_CONFIG"
    # Minio local instance
    MINIO_LOCAL_ACCESS_KEY = "MINIO_LOCAL_ACCESS_KEY"
    MINIO_LOCAL_SECRET_KEY = "MINIO_LOCAL_SECRET_KEY"
    MINIO_LOCAL_PORT = "MINIO_LOCAL_PORT"
    # S3 instance
    S3_ACCESS_KEY = "S3_ACCESS_KEY"
    S3_SECRET_KEY = "S3_SECRET_KEY"
    S3_HOST = "S3_HOST"
    S3_TLS = "S3_TLS"
    S3_PORT = "S3_PORT"
    S3_BUCKETS = "S3_BUCKETS"

    # Service Google Drive
    GOOGLE_DRIVE_ID = "GOOGLE_DRIVE_ID"
    # OIDC for Google Drive
    OIDC_ISSUER = "OIDC_ISSUER"
    OIDC_CLIENT_ID = "OIDC_CLIENT_ID"
    OIDC_CLIENT_SECRET = "OIDC_CLIENT_SECRET"

    # Service Keycloak Admin
    KEYCLOAK_USERNAME = "KEYCLOAK_USERNAME"
    KEYCLOAK_PASSWORD = "KEYCLOAK_PASSWORD"
    KEYCLOAK_BASE_URL = "KEYCLOAK_BASE_URL"
    # Keycloak container script
    PATH_KEYCLOAK_STATUS_FILE = "PATH_KEYCLOAK_STATUS_FILE"
    PATH_KEYCLOAK_SCRIPT = "PATH_KEYCLOAK_SCRIPT"
